AWSTemplateFormatVersion: "2010-09-09"
Description: CICD pipelines to automate SDLF workflows

Parameters:
  pArtifactsBucket:
    Description: The artifacts bucket used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/S3/DevOpsArtifactsBucket
  pKMSKey:
    Description: The KMS key used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/KMS/CICDKeyId

Resources:
  rLambdaLayersCodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: sdlf-codebuild
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/sdlf-*
              - Effect: Allow
                Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${pArtifactsBucket}/*
              - Effect: Allow
                Action: codecommit:GitPull
                Resource:
                  - !Sub arn:${AWS::Partition}:codecommit:${AWS::Region}:${AWS::AccountId}:sdlf-*
              - Effect: Allow
                Action:
                  - kms:CreateGrant
                  - kms:Decrypt
                  - kms:DescribeKey
                  - kms:Encrypt
                  - kms:GenerateDataKey*
                  - kms:ReEncrypt*
                Resource:
                  - !Ref pKMSKey

  rBuildLambdaLayersPackage:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Name: sdlf-cicd-build-lambda-layers
      Description: Creates a Lambda Layer containing the libraries and version numbers listed in the requirements.txt file in the repository provided
      EncryptionKey: !Ref pKMSKey
      Environment:
        EnvironmentVariables:
          - Name: ARTIFACTS_BUCKET
            Type: PLAINTEXT
            Value: !Ref pArtifactsBucket
          - Name: KMS_KEY
            Type: PLAINTEXT
            Value: !Ref pKMSKey
          - Name: AWS_PARTITION
            Type: PLAINTEXT
            Value: !Ref AWS::Partition
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        Type: LINUX_CONTAINER
      QueuedTimeoutInMinutes: 60
      ServiceRole: !GetAtt rLambdaLayersCodeBuildServiceRole.Arn
      Source:
        BuildSpec: |
          version: 0.2
          env:
            exported-variables:
              - LAYERS_CDL
          phases:
            install:
              runtime-versions:
                  python: 3.11
              commands:
                - |-
                    aws --version # version 1 installed using pip by codebuild
                    pip3 uninstall -y awscli
                    aws --version # version 2
                - pip3 install boto3
            build:
              commands:
                - |-
                    if [ -d "./layers-$ENVIRONMENT/" ]; then
                        cd "./layers-$ENVIRONMENT/" || exit
                        LAYERS=()

                        # download already-zipped layers
                        if [ -f "./external_layers.json" ]; then
                            echo "external_layers.json exists"
                            # the following assumes all declared layer names have a url associated to them
                            LAYER_NAMES=$(jq -r '.[] | keys_unsorted | .[]' external_layers.json)
                            echo "LAYER_NAMES - $LAYER_NAMES"
                            URLS=$(jq -r '.[] | .[].url' external_layers.json)
                            echo "URLS - $URLS"
                            for i in "${!LAYER_NAMES[@]}"; do
                                curl -s -L -o "${LAYER_NAMES[i]}.zip" "${URLS[i]}"
                                aws s3api put-object --bucket "$ARTIFACTS_BUCKET" \
                                                     --key "layers/$DOMAIN/$ENVIRONMENT/$TEAM/${LAYER_NAMES[i]}.zip" \
                                                     --body "${LAYER_NAMES[i]}.zip"
                                LAYERS+=("${LAYER_NAMES[i]}")
                            done
                        fi

                        echo ">>>>> Beginning build of subdirectories >>>>>"
                        for dir in ./*/
                        do
                            dir=${dir%*/}      # remove the trailing "/"
                            LAYER_NAME="${dir##*/}"    # print everything after the final "/"
                            echo "---- Looking to move to: "

                            cd "$dir"
                            echo "Moving into dir..."
                            echo "Current directory contents:"
                            ls
                            if [ -f "./requirements.txt" ]; then
                                echo "requirements.txt exists"
                                echo "-----> making temporary directory"
                                mkdir -p layer/python
                                pip3 -q install -r ./requirements.txt -t layer/python
                                cd layer/
                                zip --quiet -r "$LAYER_NAME.zip" python/ -x \*__pycache__\*
                                aws s3api put-object --bucket "$ARTIFACTS_BUCKET" \
                                                     --key "layers/$DOMAIN/$ENVIRONMENT/$TEAM/$LAYER_NAME.zip" \
                                                     --body "$LAYER_NAME.zip"
                                LAYERS+=("$LAYER_NAME")
                                cd ../..
                            fi
                            echo "============= COMPLETED DIRECTORY BUILD ============="
                        done

                        # prepare the parameter that will be fed to the cloudformation template containing all lambda layers
                        printf -v joined "%s," "${LAYERS[@]}"
                        LAYERS_CDL="${joined%,}"
                        echo "LAYERS_CDL - $LAYERS_CDL"

                        # get wheels and push them to s3
                        if [ -f "./external_wheels.json" ]; then
                            echo "external_wheels.json exists"
                            # the following assumes all declared layer names have a url associated to them
                            WHEEL_NAMES=$(jq -r '.[] | keys_unsorted | .[]' external_wheels.json)
                            echo "WHEEL_NAMES - $WHEEL_NAMES"
                            URLS=$(jq -r '.[] | .[].url' external_wheels.json)
                            echo "URLS - $URLS"
                            for i in "${!WHEEL_NAMES[@]}"; do
                                curl -s -L -o "${WHEEL_NAMES[i]}.whl" "${URLS[i]}"
                                aws s3api put-object --bucket "$ARTIFACTS_BUCKET" \
                                                     --key "layers/$DOMAIN/$ENVIRONMENT/$TEAM/${WHEEL_NAMES[i]}.zip" \
                                                     --body "${WHEEL_NAMES[i]}.whl"
                            done
                        fi
                    fi
        Type: CODEPIPELINE
      TimeoutInMinutes: 20

  ######## SSM OUTPUTS #########
  rBuildLambdaLayersPackageSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeBuild/BuildLambdaLayersPackage
      Type: String
      Value: !Ref rBuildLambdaLayersPackage
      Description: Name of the CodeBuild job that creates a Lambda Layer containing the libraries and version numbers listed in the requirements.txt file in the repository provided
