[project]
name = "sdlf-dataset"
version = "2.10.0"
description = "AWS Serverless Data Lake Framework"
readme = "README.md"
authors = [
    { name = "Amazon Web Services" }
]
license = "MIT-0"
requires-python = ">=3.12"
dependencies = [
    "aws-cdk-aws-glue-alpha>=2.187.0a0",
    "aws-cdk-aws-scheduler-alpha>=2.186.0a0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/"]
exclude = ["**/*.yaml"]

[tool.hatch.build.targets.wheel.sources]
"src" = "sdlf"
